version: '3'

services:
  db:
    image: postgres
    ports:
      - 5432:5432
    environment:
      POSTGRES_DB: dlogistic
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin

  pgadmin:
    image: chorss/docker-pgadmin4
    ports:
      - 5050:5050
  web:
    build: .
    container_name: django_crm
    command: python3 manage.py runserver 0.0.0.0:8000
    volumes:
      - /home/mykityuk/work/PycharmProjects/dlogistic:/code
    ports:
      - "8000:8000"

